### ISSUE TITLE
Error on running pockyt reg

### ISSUE THREAD

**Issue by jml** [achembarpu/pockyt#21]
Hello! 

I just heard about pockyt. I installed it via `pipx install pockyt` (my first use of `pipx`) and then ran `pockyt reg`. I got the following error:

```
---------------------------------------------------------------------
Bug Report :
`pockyt` has encountered an error! Please submit this bug report at
` https://www.github.com/achembarpu/pockyt/issues/new `.
---------------------------------------------------------------------
Python Version:
3.10.5 (main, Jul 31 2022, 08:19:00) [Clang 13.1.6 (clang-1316.0.21.2.5)]
---------------------------------------------------------------------
Installed Packages:
parse - 1.19.0
pockyt - 1.4.6
setuptools - 65.1.0
pip - 22.2.2
wheel - 0.37.1
---------------------------------------------------------------------
Commmand:
reg
---------------------------------------------------------------------
Error Message:
Traceback (most recent call last):
  File "/Users/jml/.local/pipx/venvs/pockyt/lib/python3.10/site-packages/pockyt/pockyt.py", line 227, in main
    error = app.run()
  File "/Users/jml/.local/pipx/venvs/pockyt/lib/python3.10/site-packages/pockyt/pockyt.py", line 214, in run
    auth.setup()
  File "/Users/jml/.local/pipx/venvs/pockyt/lib/python3.10/site-packages/pockyt/auth.py", line 97, in setup
    self._obtain_access_token()
  File "/Users/jml/.local/pipx/venvs/pockyt/lib/python3.10/site-packages/pockyt/auth.py", line 64, in _obtain_access_token
    response = Network.post_request(API.ACCESS_TOKEN_URL, payload)
  File "/Users/jml/.local/pipx/venvs/pockyt/lib/python3.10/site-packages/pockyt/wrapper.py", line 136, in post_request
    response = Response(urlopen(request))
  File "/Users/jml/.pyenv/versions/3.10.5/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/jml/.pyenv/versions/3.10.5/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/jml/.pyenv/versions/3.10.5/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/jml/.pyenv/versions/3.10.5/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Users/jml/.pyenv/versions/3.10.5/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/jml/.pyenv/versions/3.10.5/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
---------------------------------------------------------------------
```

When creating the application, I entered "Pockyt" as the name, "Command-line client for Pocket" as the description, selected "Add", "Remove", and "Modify" as the permissions and "Mac" as the platform. Naturally I accepted the terms of service.

I then copy/pasted the consumer key into the terminal, and clicked "Authorize" in my browser. The browser redirected me to the Github repo and the command-line showed the error you see above.

I repeated all of the steps in case the 500 represents an intermittent server error. All of this took place at roughly 2022-08-19T06:00:00+00:00.

Thanks!

**Comment by shredthaGNAR** [comment]
same

**Comment by jamespo** [comment]
I have a pull request / fork which fixes this, one line change: https://github.com/achembarpu/pockyt/pull/22
