### ISSUE TITLE
~/.local/bin/pockyt get   error

### ISSUE THREAD

**Issue by zbagoly** [achembarpu/pockyt#23]
This worked earlier, then  after deleting a few hundred item with pockyt  mod -d -i redirect  , it stopped working:

 $ ~/.local/bin/pockyt get        

---------------------------------------------------------------------
Bug Report :
`pockyt` has encountered an error! Please submit this bug report at 
` https://www.github.com/achembarpu/pockyt/issues/new `.
---------------------------------------------------------------------
Python Version:
3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
---------------------------------------------------------------------
Installed Packages:
zipp - 3.17.0
yattag - 1.15.1
yarl - 1.8.2
xmodem - 0.4.7
wxpython - 4.2.1
websocket-client - 1.5.3
webcolors - 1.13
userpath - 1.9.1
uri-template - 1.2.0
typing-extensions - 4.6.3
tomli - 2.0.1
tinycss2 - 1.2.1
threadpoolctl - 3.2.0
sniffio - 1.3.0
six - 1.10.0
semantic-version - 2.10.0
scikit-learn - 1.3.1
rfc3986-validator - 0.1.1
rfc3339-validator - 0.1.4
requests - 2.9.1
python-json-logger - 2.0.7
pysimplegui - 4.60.5
pyserial - 3.5
pymupdfb - 1.23.7
pymupdf - 1.23.7
pygame - 2.5.2
pyfftw - 0.13.1
pycryptodome - 3.20.0
py-datastruct - 1.0.0
progress - 1.2
prettytable - 3.9.0
pockyt - 1.4.6
pocket-cli - 0.1.6
pocket-api - 0.1.5
pipx - 1.2.0
pip - 23.3.1
pillow - 10.1.0
pdfcropmargins - 2.0.3
parse - 1.20.1
packaging - 23.1
overrides - 7.3.1
openai - 0.26.2
numpy - 1.25.2
notebook-shim - 0.2.3
nmf - 0.0.6
nbformat - 5.9.0
nbconvert - 7.4.0
nbclient - 0.8.0
multidict - 6.0.4
mistune - 2.0.5
miss-hit - 0.9.42
miss-hit-core - 0.9.42
markupsafe - 2.1.3
ltchiptool - 4.10.1
jupyterlab - 4.0.2
jupyterlab-server - 2.22.1
jupyterlab-pygments - 0.2.2
jupyter-server - 2.6.0
jupyter-server-terminals - 0.4.4
jupyter-lsp - 2.2.0
jupyter-events - 0.6.3
jsonschema - 4.17.3
jsonpointer - 2.3
json5 - 0.9.14
joblib - 1.3.2
jinja2 - 3.1.2
isoduration - 20.11.0
importlib-resources - 6.1.0
hexdump - 3.3
healpy - 1.16.2
future - 0.15.2
frozenlist - 1.3.3
fqdn - 1.5.1
finufft - 2.1.0
fastrlock - 0.8.2
fastjsonschema - 2.17.1
exceptiongroup - 1.1.1
esp-flasher - 1.4.1
colorama - 0.4.6
click - 6.2
chirp - 20230924
charset-normalizer - 2.1.1
bk7231tools - 1.5.4
bitstruct - 8.19.0
babel - 2.12.1
async-timeout - 4.0.2
async-lru - 2.0.2
arrow - 1.2.3
argcomplete - 3.1.2
anyio - 3.7.0
aiosignal - 1.3.1
aiohttp - 3.8.3
traitlets - 5.9.0
tornado - 6.3.2
stack-data - 0.6.2
qtpy - 2.3.1
qtconsole - 5.4.3
pyzmq - 25.1.0
python-dateutil - 2.8.2
pure-eval - 0.2.2
prompt-toolkit - 3.0.38
platformdirs - 3.5.3
nest-asyncio - 1.5.6
matplotlib-inline - 0.1.6
jupyter - 1.0.0
jupyter-core - 5.3.0
jupyter-console - 6.6.3
jupyter-client - 8.2.0
ipython - 8.14.0
ipykernel - 6.23.1
importlib-metadata - 6.6.0
executing - 1.2.0
debugpy - 1.6.7
comm - 0.1.3
asttokens - 2.2.1
zope.interface - 5.2.0
zope.hookable - 5.0.1
zope.event - 4.4
zope.component - 4.3.0
zeroconf - 0.26.1
youtube-dl - 2021.6.6
yaswfp - 0.9.3
yara-python - 4.0.4
xpra - 3.0.13
xlwt - 1.3.0
xlsxwriter - 1.1.2
xlrd - 1.2.0
xdg - 5
wsaccel - 0.6.2
wrapt - 1.12.1
wifite - 2.5.8
widgetsnbextension - 2.0.0
wheel - 0.34.2
wfuzz - 3.1.0
werkzeug - 1.0.1
webencodings - 0.5.1
wcwidth - 0.1.9
watchdog - 1.0.2
wapiti3 - 3.0.4
waitress - 1.4.4
wadllib - 1.3.5
vobject - 0.9.6.1
vispy - 0.6.6
vinetto - 0.8.0
vine - 5.0.0
urllib3 - 1.26.5
uritools - 3.0.0
uritemplate - 3.0.1
upstream-ontologist - 0.1.22
unidiff - 0.5.5
unidecode - 1.2.0
unattended-upgrades - 0.1
u-msgpack-python - 2.3.0
typed-ast - 1.4.2
txaio - 20.4.1
twisted - 20.3.0
tqdm - 4.57.0
toolz - 0.9.0
toml - 0.10.1
tld - 0.11.11
tinycss - 0.4
tifffile - 2021.2.1
theano - 1.0.5
testpath - 0.4.4
terminado - 0.9.2
tables - 3.6.1
systemd-python - 234
sympy - 1.7.1
stepic - 0.5.0
sqlparse - 0.4.1
sqlalchemy - 1.3.22
sphinx - 3.4.3
speg - 0.3
sparqlwrapper - 1.8.5
soupsieve - 2.2.1
sortedcontainers - 2.1.0
snuggs - 1.4.7
snowballstemmer - 2.1.0
simplejson - 3.17.2
simplegeneric - 0.8.1
shellescape - 3.4.1
setuptools - 52.0.0
setproctitle - 1.2.1
service-identity - 18.1.0
send2trash - 1.6.0b1
secretstorage - 3.3.1
scour - 0.38.2
scipy - 1.6.0
scikit-image - 0.18.1
schema-salad - 7.0.20210124093443
ruffus - 2.8.4
ruamel.yaml - 0.16.12
ruamel.yaml.clib - 0.2.2
rsa - 4.0
roman - 2.0.0
requests-toolbelt - 0.9.1
requests-futures - 1.0.0
reportlab - 3.5.59
reportbug - 7.10.3+deb11u1
rencode - 1.0.6
redis - 3.5.3
rdflib - 5.0.0
rdflib-jsonld - 0.5.0
rasterio - 1.2.0
ranger-fm - 1.9.3
quodlibet - 4.3.0
pyyaml - 5.3.1
pyxdg - 0.27
pyxattr - 0.7.2
pywavelets - 1.1.1
pytz - 2021.1
pytsk3 - 20200117
pytrie - 0.2
pythonqwt - 0.8.3
python-xlib - 0.29
python-xapp - 2.0.2
python-vlc - 3.0.11115
python-snappy - 0.5.3
python-sane - 2.9.1
python-poppler-qt5 - 0.75.0
python-pam - 1.8.4
python-memcached - 1.58
python-magic - 0.4.20
python-lzo - 1.12
python-libtorrent - 1.2.9
python-gitlab - 2.5.0
python-gflags - 1.5.1
python-debianbts - 3.1.0
python-debian - 0.1.39
python-daemon - 2.2.4
python-consul - 0.7.1
python-casacore - 3.3.1
python-apt - 2.2.1
pytest - 6.0.2
pytest-remotedata - 0.3.2
pytest-openfiles - 0.5.0
pytest-filter-subpackage - 0.1.1
pytest-doctestplus - 0.9.0
pytest-cov - 2.10.1
pytest-astropy - 0.8.0
pytest-astropy-header - 0.1.2
pytest-arraydiff - 0.3
pysocks - 1.7.1
pysnmp - 4.4.12
pysmi - 0.3.2
pysmbc - 1.0.23
pysimplesoap - 1.16.2
pyrsistent - 0.15.5
pyrfc3339 - 1.1
pyregfi - 1.0.1.0
pyqtgraph - 0.11.1
pyqt5 - 5.15.2
pyqt5-sip - 12.8.1
pyqrcode - 1.2.1
pypng - 0.0.20
pypdf2 - 1.26.0
pyparsing - 2.4.7
pyopenssl - 20.0.1
pyopengl - 3.1.5
pynacl - 1.4.0
pympress - 1.5.3
pylint - 2.7.2
pykerberos - 1.1.14
pyjwt - 1.7.1
pyinotify - 0.9.6
pyicu - 2.5
pyhamcrest - 1.9.0
pygraphviz - 1.7
pygpu - 0.7.6
pygobject - 3.38.0
pygments - 2.7.1
pygithub - 1.43.7
pyflakes - 2.2.0
pyerfa - 1.7.2
pyenchant - 3.2.0
pydot - 1.4.2
pycurl - 7.43.0.6
pycups - 2.0.1
pycryptodomex - 3.9.7
pycodestyle - 2.6.0
pycairo - 1.16.2
pyasn1 - 0.4.8
pyasn1-modules - 0.2.1
pyaes - 1.6.1
py3dns - 3.2.1
py - 1.10.0
py-ubjson - 0.16.1
py-cpuinfo - 5.0.0
psycopg2 - 2.8.6
psutil - 5.8.0
pssh - 2.3.1
prov - 1.5.2
protobuf - 3.12.4
prometheus-client - 0.9.0
ply - 3.11
pluggy - 0.13.0
plastex - 2.1
plaso - 20201007
pivy - 0.6.5
pikepdf - 1.17.3+dfsg
pickleshare - 0.7.5
pexpect - 4.8.0
pep8 - 1.7.1
pefile - 2019.4.18
pdfminer.six - 20200726
pbr - 5.5.0
patiencediff - 0.2.1
patator - 0.9
partd - 1.0.0
parso - 0.8.1
parsedatetime - 2.6
paramiko - 2.7.2
parameterized - 0.7.0
pandocfilters - 1.4.3
pandas - 1.1.5
openpyxl - 3.0.3
olefile - 0.46
odfpy - 1.4.1
ocrmypdf - 10.3.1+dfsg
oauthlib - 3.1.0
oauth2client - 4.1.2
numpysane - 0.31
numexpr - 2.7.2
numba - 0.52.0
notebook - 6.2.0
nose2 - 0.9.2
nose - 1.3.7
networkx - 2.5
netaddr - 0.7.19
mysqlclient - 1.4.4
mypy - 0.812
mypy-extensions - 0.4.3
mutagen - 1.45.1
musicbrainzngs - 0.7.1
msgpack - 1.0.0
mpmath - 0.0.0
mpi4py - 3.0.3
more-itertools - 4.2.0
monotonic - 1.5
mock - 4.0.3
mercurial - 5.6.1
mccabe - 0.6.1
matplotlib - 3.3.4
matplotlib-venn - 0.11.6
markdown - 3.3.4
mako - 1.1.3
lz4 - 3.1.3+dfsg
lxml - 4.6.3
louis - 3.16.0
logilab-common - 1.8.1
lockfile - 0.12.2
locket - 0.2.0
llvmlite - 0.35.0
llfuse - 1.3.8
ldapdomaindump - 0.9.3
ldap3 - 2.8.1
lazy-object-proxy - 0.0.0
lazr.uri - 1.0.5
lazr.restfulclient - 0.14.2
launchpadlib - 1.10.13
krop - 0.6.0
kombu - 5.0.2
kiwisolver - 1.3.1
keyrings.alt - 4.0.2
keyring - 22.0.1
josepy - 1.2.0
jeepney - 0.6.0
jedi - 0.18.0
jdcal - 1.0
itsdangerous - 1.1.0
isort - 5.6.4
isodate - 0.6.0
ipywidgets - 6.0.0
ipython-genutils - 0.2.0
ipy - 1.1
invoke - 1.4.1
iniconfig - 0.0.0
incremental - 17.5.0
impacket - 0.9.22
img2pdf - 0.4.0
imagesize - 1.2.0
imageio - 2.4.1
ifaddr - 0.1.7
idna - 2.10
hypothesis - 5.43.3
hyperlink - 19.0.0
humanfriendly - 9.1
httplib2 - 0.18.1
html5lib - 1.1
hashid - 3.1.4
h5py - 2.10.0
h5py.-debian-h5py-serial - 2.10.0
gyp - 0.1
gssapi - 1.6.1
grokevt - 0.5
greenlet - 0.4.17
gpg - 1.14.0-unknown
google-auth - 1.5.1
google-auth-httplib2 - 0.0.4
google-api-python-client - 1.7.11
gnuplotlib - 0.37
gnuplot-py - 1.8
gdal - 3.2.2
gcalcli - 4.3.0
fsspec - 0.8.4
frozendict - 1.2
freetype-py - 2.2.0
flask - 1.1.2
flake8 - 3.8.4
fitsio - 1.1.4
feedparser - 5.2.1
fastimport - 0.9.8
fasteners - 0.14.1
fail2ban - 0.11.2
exifread - 2.3.2
et-xmlfile - 1.0.1
ephem - 3.7.7.1
entrypoints - 0.3
elasticsearch - 7.1.0
ecdsa - 0.16.1
dulwich - 0.20.15
dugong - 3.8.1
dtfabric - 20200621
docutils - 0.16
dnspython - 2.0.0
django - 2.2.28
django-celery-results - 2.0.0
distro - 1.5.0
distro-info - 1.0+deb11u1
dfwinreg - 20201006
dfvfs - 20201219
dfdatetime - 20200824
devscripts - 2.21.3+deb11u1
deprecated - 1.2.11
defusedxml - 0.6.0
decorator - 4.4.2
debmutate - 0.20
deap - 1.3.1
dbus-python - 1.2.16
dask - 2021.1.0+dfsg
cython - 0.29.21
cycler - 0.10.0
cwltool - 3.0.20210124104916
cupshelpers - 1.0
cson - 0.8
cryptography - 3.3.2
coverage - 5.1
cov-core - 1.15.0
constantly - 15.1.0
configobj - 5.0.6
configargparse - 1.2.3
coloredlogs - 7.3
cloudpickle - 1.6.0
cligj - 0.7.1
click-threading - 0.4.4
click-repl - 0.1.6
click-plugins - 1.1.1
click-log - 0.2.1
click-didyoumean - 0.0.3
chrome-gnome-shell - 0.0.0
chardet - 4.0.0
certifi - 2020.6.20
certbot - 1.12.0
celery - 5.0.0
cbor - 1.0.0
catkin - 0.8.9
catkin-pkg - 0.4.23
cachetools - 4.2.1
cachecontrol - 0.12.6
brz-debian - 3.0.0
brotli - 1.0.9
brlapi - 0.8.2
breezy - 3.1.0
bottleneck - 1.2.1
bottle - 0.12.19
blosc - 1.9.2
blinker - 1.4
bleach - 3.2.1
binwalk - 2.2.1
billiard - 3.6.3.0
beautifulsoup4 - 4.9.3
bcrypt - 3.1.7
backcall - 0.2.0
autopep8 - 1.5.5
automat - 20.2.0
autobahn - 17.10.1
attrs - 20.3.0
atomicwrites - 1.4.0
astropy - 4.2
astroid - 2.5.1
asn1crypto - 1.4.0
asdf - 2.7.2
artifacts - 20201106
argon2-cffi - 18.3.0
argh - 0.26.2
arcp - 0.2.1
arandr - 0.1.10
apt-xapian-index - 0.49
apsw - 3.34.0.post1
anyjson - 0.3.3
amqp - 5.0.3
alabaster - 0.7.8
ajpy - 0.0.4
affine - 2.3.0
acme - 1.12.0
---------------------------------------------------------------------
Commmand:
get
---------------------------------------------------------------------
Error Message:
Traceback (most recent call last):
  File "/home/zsolt/.local/lib/python3.9/site-packages/pockyt/pockyt.py", line 227, in main
    error = app.run()
  File "/home/zsolt/.local/lib/python3.9/site-packages/pockyt/pockyt.py", line 220, in run
    pocket.run()
  File "/home/zsolt/.local/lib/python3.9/site-packages/pockyt/client.py", line 226, in run
    self._get()
  File "/home/zsolt/.local/lib/python3.9/site-packages/pockyt/client.py", line 157, in _get
    self._api_request()
  File "/home/zsolt/.local/lib/python3.9/site-packages/pockyt/client.py", line 36, in _api_request
    self._response = Network.post_request(self._api_endpoint,
  File "/home/zsolt/.local/lib/python3.9/site-packages/pockyt/wrapper.py", line 136, in post_request
    response = Response(urlopen(request))
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
---------------------------------------------------------------------

**Comment by zbagoly** [comment]
After registering a new reg and a new app, it works again...
